# Generated by Django 5.1.6 on 2025-04-15 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id_gambar', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pengguna', models.IntegerField()),
                ('id_direktori', models.IntegerField()),
                ('id_dataset', models.BigIntegerField()),
                ('nama_file', models.CharField(max_length=50)),
                ('ukuran_file', models.IntegerField()),
                ('tanggal_dibuat', models.DateField()),
                ('format_file', models.CharField(max_length=11)),
                ('tanggal_pengambilan', models.IntegerField()),
                ('model_kamera', models.IntegerField()),
                ('lebar', models.IntegerField()),
                ('tinggi', models.IntegerField()),
                ('lokasi_pengambilan', models.IntegerField()),
                ('id_pembuat', models.IntegerField()),
                ('tanggal_buat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileJob',
            fields=[
                ('id_profile_job', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pengguna', models.IntegerField()),
                ('nama_profile_job', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('isu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anotasi',
            fields=[
                ('id_anotasi', models.BigAutoField(primary_key=True, serialize=False)),
                ('koordinat_x', models.IntegerField()),
                ('koordinat_y', models.IntegerField()),
                ('lebar', models.IntegerField()),
                ('tinggi', models.IntegerField()),
                ('id_gambar', models.ForeignKey(db_column='id_gambar', on_delete=django.db.models.deletion.CASCADE, to='reviewer.gambar')),
            ],
        ),
        migrations.CreateModel(
            name='IsuAnotasi',
            fields=[
                ('id_isu_anotasi', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('id_pembuat', models.IntegerField()),
                ('tanggal_buat', models.DateTimeField()),
                ('nama_tipe_isu', models.IntegerField()),
                ('id_parent_isu_anotasi', models.BigIntegerField(blank=True, null=True)),
                ('id_anotasi', models.ForeignKey(db_column='id_anotasi', on_delete=django.db.models.deletion.CASCADE, to='reviewer.anotasi')),
            ],
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id_job_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_job_assignment_annotator', models.BigIntegerField()),
                ('id_job_assignment_reviewer', models.BigIntegerField()),
                ('status_pekerjaan', models.CharField(max_length=1)),
                ('id_gambar', models.ForeignKey(db_column='id_gambar', on_delete=django.db.models.deletion.CASCADE, to='reviewer.gambar')),
                ('id_profile_job', models.ForeignKey(db_column='id_profile_job', on_delete=django.db.models.deletion.CASCADE, to='reviewer.profilejob')),
            ],
        ),
        migrations.CreateModel(
            name='IsuImage',
            fields=[
                ('id_isu_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('id_pembuat', models.IntegerField()),
                ('tanggal_buat', models.DateTimeField()),
                ('nama_tipe_isu', models.IntegerField()),
                ('id_parent_isu_image', models.BigIntegerField(blank=True, null=True)),
                ('id_job_item', models.ForeignKey(db_column='id_job_item', on_delete=django.db.models.deletion.CASCADE, to='reviewer.jobitem')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentasi',
            fields=[
                ('id_segmentasi', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_tipe_segmentasi', models.IntegerField()),
                ('label_segmentasi', models.CharField(max_length=20)),
                ('warna_segmentasi', models.CharField(max_length=10)),
                ('koordinat', models.IntegerField()),
                ('id_job_item', models.ForeignKey(db_column='id_job_item', on_delete=django.db.models.deletion.CASCADE, to='reviewer.jobitem')),
            ],
        ),
        migrations.AddField(
            model_name='anotasi',
            name='id_segmentasi',
            field=models.ForeignKey(db_column='id_segmentasi', on_delete=django.db.models.deletion.CASCADE, to='reviewer.segmentasi'),
        ),
    ]
