# Generated by Django 5.1.6 on 2025-04-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(max_length=50)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='id_pengguna',
            field=models.ForeignKey(db_column='id_pengguna', on_delete=django.db.models.deletion.CASCADE, to='reviewer.pengguna'),
        ),
    ]
