# Generated by Django 5.1.6 on 2025-04-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_pengguna_alter_profilejob_id_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='id_pengguna',
            field=models.ForeignKey(db_column='id_pengguna', on_delete=django.db.models.deletion.CASCADE, to='reviewer.pengguna'),
        ),
    ]
