# Generated by Django 5.1.6 on 2025-05-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_alter_gambar_id_pengguna'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeRole',
            fields=[
                ('id_tipe_role', models.BigIntegerField(max_length=19, primary_key=True, serialize=False)),
                ('nama_tipe_role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('tanggal_registrasi', models.DateTimeField(auto_created=True)),
                ('id_member', models.BigIntegerField(max_length=19, primary_key=True, serialize=False)),
                ('email_member', models.CharField(max_length=50)),
                ('no_hp_member', models.IntegerField(max_length=10)),
                ('afiliasi', models.CharField(max_length=50)),
                ('peran', models.CharField(max_length=50)),
                ('id_pengguna', models.ForeignKey(db_column='id_pengguna', on_delete=django.db.models.deletion.CASCADE, to='reviewer.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id_member_role', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('is_active', models.CharField(max_length=1)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.CASCADE, to='reviewer.member')),
                ('id_tipe_role', models.ForeignKey(db_column='id_tipe_role', on_delete=django.db.models.deletion.CASCADE, to='reviewer.tiperole')),
            ],
        ),
    ]
