# Generated by Django 5.1.6 on 2025-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_tiperole_member_memberrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='afiliasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_member',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_member',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='no_hp_member',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='id_member_role',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tiperole',
            name='id_tipe_role',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
