# Generated by Django 5.1.6 on 2025-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_alter_member_afiliasi_alter_member_email_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_member',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
