# Generated by Django 5.1.6 on 2025-05-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_alter_member_id_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
