# Generated by Django 5.1.6 on 2025-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0007_alter_pengguna_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilejob',
            name='deskripsi',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='isu',
            field=models.CharField(max_length=500),
        ),
    ]
