# Generated by Django 5.1.6 on 2025-06-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0008_alter_profilejob_deskripsi_alter_profilejob_isu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='tanggal_pengambilan',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PolygonTool',
            fields=[
                ('id_polygon_tool', models.BigAutoField(primary_key=True, serialize=False)),
                ('koordinat_xn', models.IntegerField()),
                ('koordinat_yn', models.IntegerField()),
                ('id_anotasi', models.ForeignKey(db_column='id_anotasi', on_delete=django.db.models.deletion.CASCADE, to='reviewer.anotasi')),
            ],
        ),
    ]
