# Generated by Django 5.1.6 on 2025-06-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0009_alter_gambar_tanggal_pengambilan_polygontool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeSegmentasi',
            fields=[
                ('id_tipe_segmentasi', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_tipe_segmentasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='segmentasi',
            name='id_tipe_segmentasi',
            field=models.ForeignKey(db_column='id_tipe_segmentasi', on_delete=django.db.models.deletion.CASCADE, to='reviewer.tipesegmentasi'),
        ),
    ]
