# Generated by Django 5.2.3 on 2025-08-25 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='master.jobimage')),
                ('segmentation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.segmentationtype')),
            ],
            options={
                'ordering': ['job', 'label'],
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='master.segmentation'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentation',
            unique_together={('job', 'label')},
        ),
    ]
