# Generated by Django 5.1.7 on 2025-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_customuser_managers_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('member', 'Member')], default='guest', max_length=20),
        ),
    ]
