# Generated by Django 5.1.7 on 2025-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_count', models.IntegerField(default=0)),
                ('segmentation_type', models.CharField(choices=[('semantic', 'Semantic'), ('instance', 'Instance'), ('panoptic', 'Panoptic')], max_length=20)),
                ('shape_type', models.CharField(choices=[('bounding_box', 'Bounding Box'), ('polygon', 'Polygon')], max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_assign', 'Not assign'), ('in_progress', 'In progress'), ('finish', 'Finish')], default='not_assign', max_length=20)),
            ],
        ),
    ]
