# Generated by Django 5.1.7 on 2025-05-07 20:27

import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_jobimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to=master.models.job_image_path),
        ),
    ]
