# Generated by Django 5.1.7 on 2025-05-15 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_jobimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='worker_annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='worker_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='status',
            field=models.CharField(choices=[('not_assign', 'Not Assigned'), ('in_progress', 'In Progress'), ('finish', 'Finished')], default='not_assign', max_length=20),
        ),
    ]
