# Generated by Django 5.1.7 on 2025-05-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_jobprofile_worker_annotator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='jobimage',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('in_review', 'In Review'), ('in_rework', 'In Rework'), ('finished', 'Finished'), ('Issue', 'Issue')], default='unannotated', max_length=20),
        ),
    ]
