# Generated by Django 5.1.7 on 2025-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_remove_jobimage_uploaded_at_jobimage_annotator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='label_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='review_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
