# Generated by Django 5.1.7 on 2025-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_jobimage_label_time_jobimage_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('annotated', 'Annotated'), ('in_review', 'In Review'), ('in_rework', 'In Rework'), ('finished', 'Finished'), ('Issue', 'Issue')], default='unannotated', max_length=20),
        ),
    ]
