# Generated by Django 5.1.7 on 2025-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_add_annotated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
