# Generated by Django 5.1.7 on 2025-06-16 09:46

import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_add_priority_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to=master.models.job_image_path),
        ),
    ]
