# Generated by Django 5.1.7 on 2025-06-16 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_update_image_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
