# Generated by Django 5.1.7 on 2025-06-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_update_image_upload_path'),
        ('master', '0014_add_date_created_to_jobprofile'),
    ]

    operations = [
    ]
