# Generated by Django 5.1.7 on 2025-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("master", "0002_auto_20250825_1630"),

        ("master", "0018_jobprofile_estimated_duration_jobprofile_project_id_and_more"),

    ]

    operations = [
        migrations.AddField(
            model_name="jobprofile",
            name="estimated_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="project_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
