# Generated by Django 5.2.3 on 2025-08-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_jobprofile_estimated_duration_jobprofile_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('in_progress', 'In Progress'), ('annotated', 'Annotated'), ('in_review', 'In Review'), ('in_rework', 'In Rework'), ('finished', 'Finished'), ('issue', 'Issue')], default='unannotated', max_length=20),
        ),
    ]
