# Generated by Django 5.1.7 on 2025-07-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0019_jobprofile_estimated_duration_jobprofile_project_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("x_min", models.FloatField()),
                ("y_min", models.FloatField()),
                ("x_max", models.FloatField()),
                ("y_max", models.FloatField()),
                ("is_auto_generated", models.BooleanField(default=True)),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="master.jobimage",
                    ),
                ),
            ],
        ),
    ]
