# Generated by Django 5.2.3 on 2025-08-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_alter_jobimage_status'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE master_annotation RENAME COLUMN tool_used_id TO tool_id;",
            reverse_sql="ALTER TABLE master_annotation RENAME COLUMN tool_id TO tool_used_id;"
        ),
    ]
