# Generated by Django 5.2.3 on 2025-08-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_rename_tool_used_id_to_tool_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE master_annotation 
            ADD COLUMN annotator_id bigint,
            ADD COLUMN reviewer_id bigint,
            ADD COLUMN image_id bigint,
            ADD COLUMN label varchar(100),
            ADD COLUMN x_min double precision,
            ADD COLUMN y_min double precision,
            ADD COLUMN x_max double precision,
            ADD COLUMN y_max double precision,
            ADD COLUMN is_auto_generated boolean DEFAULT true,
            ADD COLUMN status varchar(20) DEFAULT 'pending',
            ADD COLUMN reviewed_at timestamp with time zone;
            
            ALTER TABLE master_annotation 
            ADD CONSTRAINT master_annotation_annotator_id_fkey 
            FOREIGN KEY (annotator_id) REFERENCES master_customuser(id) DEFERRABLE INITIALLY DEFERRED;
            
            ALTER TABLE master_annotation 
            ADD CONSTRAINT master_annotation_reviewer_id_fkey 
            FOREIGN KEY (reviewer_id) REFERENCES master_customuser(id) DEFERRABLE INITIALLY DEFERRED;
            
            ALTER TABLE master_annotation 
            ADD CONSTRAINT master_annotation_image_id_fkey 
            FOREIGN KEY (image_id) REFERENCES master_jobimage(id) DEFERRABLE INITIALLY DEFERRED;
            
            CREATE INDEX master_annotation_annotator_id_idx ON master_annotation(annotator_id);
            CREATE INDEX master_annotation_reviewer_id_idx ON master_annotation(reviewer_id);
            CREATE INDEX master_annotation_image_id_idx ON master_annotation(image_id);
            """,
            reverse_sql="""
            ALTER TABLE master_annotation 
            DROP CONSTRAINT IF EXISTS master_annotation_annotator_id_fkey,
            DROP CONSTRAINT IF EXISTS master_annotation_reviewer_id_fkey,
            DROP CONSTRAINT IF EXISTS master_annotation_image_id_fkey;
            
            DROP INDEX IF EXISTS master_annotation_annotator_id_idx;
            DROP INDEX IF EXISTS master_annotation_reviewer_id_idx;
            DROP INDEX IF EXISTS master_annotation_image_id_idx;
            
            ALTER TABLE master_annotation 
            DROP COLUMN IF EXISTS annotator_id,
            DROP COLUMN IF EXISTS reviewer_id,
            DROP COLUMN IF EXISTS image_id,
            DROP COLUMN IF EXISTS label,
            DROP COLUMN IF EXISTS x_min,
            DROP COLUMN IF EXISTS y_min,
            DROP COLUMN IF EXISTS x_max,
            DROP COLUMN IF EXISTS y_max,
            DROP COLUMN IF EXISTS is_auto_generated,
            DROP COLUMN IF EXISTS status,
            DROP COLUMN IF EXISTS reviewed_at;
            """
        ),
    ]
