# Generated by Django 5.2.3 on 2025-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_add_missing_annotation_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
