# Generated by Django 5.1.7 on 2025-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0023_alter_annotation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
