# Generated by Django 5.2.3 on 2025-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_annotation_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
