# Generated by Django 5.1.7 on 2025-08-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0024_alter_annotation_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="created_at",
        ),
    ]
