# Generated by Django 5.2.3 on 2025-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_auto_20250826_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
