# Generated by Django 5.2.3 on 2025-08-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_auto_20250826_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='master.segmentation'),
        ),
    ]
