# Generated by Django 5.2.3 on 2025-08-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_auto_20250826_1059'),
    ]

    operations = [
        # First, drop the table and recreate it with correct structure
        migrations.RunSQL(
            "DROP TABLE IF EXISTS master_polygonpoint CASCADE;",
            reverse_sql="-- Cannot reverse drop table"
        ),
        
        # Recreate the table with correct structure
        migrations.CreateModel(
            name='PolygonPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('order_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_points', to='master.segmentation')),
            ],
            options={
                'ordering': ['segmentation', 'order_index'],
            },
        ),
        
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name='polygonpoint',
            unique_together={('segmentation', 'order_index')},
        ),
    ]
